steps:
  - name: gcr.io/cloud-builders/gcloud
    id: setting
    entrypoint: 'bash'
    args: [ '-c', "gcloud secrets versions access latest --secret=LINE_TOKEN --format='get(payload.data)' | tr '_-' '/+' | base64 -d > line_token.txt" ]

  - name: 'python:3.8-slim'
    id: test
    entrypoint: 'bash'
    args:
      - -c
      - |
        pip install -r requirements.txt
        pytest -s ./
    env:
      - 'PROJECT=$PROJECT_ID'
      - 'TOPIC=$_PS_TOPIC_NAME'
      - 'GCLOUD_PROJECT=$PROJECT_ID'
      - 'LINE_TOKEN=$$LINE'
    secretEnv: ['LINE']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy
    entrypoint: 'bash'
    args:
      - gcloud
      - functions
      - deploy
      - akiyabank_nagato
      - --region=asia-northeast1
      - --source=.
      - --entry-point=akiyabank_nagato
      - --runtime=python38
      - --trigger-topic=start_watch
    env:
      - 'LINE_TOKEN=$$LINE'
    secretEnv: ['LINE']

availableSecrets:
  secretManager:
  - versionName: projects/305190566977/secrets/LINE/versions/1
    env: 'LINE'
