 steps:

  - name: 'python:3.8-slim'
    id: Test
    entrypoint: /bin/sh
    args:
    - -c
    - |
      pip install -r requirements.txt
      pytest -s ./
    env:
    - 'PROJECT=$PROJECT_ID'
    - 'TOPIC=$_PS_TOPIC_NAME'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    args:
    - gcloud
    - functions
    - deploy
    - akiyabank_nagato
    - --region           = asia-northeast1
    - --source           =.
    - --entry-point      = main
    - --runtime          = python38
