steps:

  - name: 'python:3.8-slim'
    id: test
    entrypoint: 'bash'
    args:
      - -c
      - |
        pip install -r requirements.txt
        pytest -s ./
    env:
      - 'PROJECT=$PROJECT_ID'
      - 'TOPIC=$_PS_TOPIC_NAME'
      - 'GCLOUD_PROJECT=$PROJECT_ID'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: deploy
    entrypoint: 'bash'
    args:
      - gcloud
      - functions
      - deploy
      - akiyabank_nagato
      - --region=asia-northeast1
      - --source=.
      - --entry-point=akiyabank_nagato
      - --runtime=python38
      - --trigger-topic=start_watch
